#ifndef WINIDS_H
#define WINIDS_H

enum WinIDs {
    WINID_ZOOM = 1,
    WINID_NEWLEVEL,

    WINID_TEXTURELIST,
    WINID_TEXTUREINFO,
    WINID_NEWTEXTURE,

    WINID_LAYERLIST,
    WINID_LAYERINFO,

    WINID_PALETTE,

    WINID_OBJECTLIST,
    WINID_NEWOBJECT,
    WINID_OBJECTINFO,
    WINID_RENAMEOBJECT,
    
    WINID_NEWPROPERTY,
    WINID_RENAMEPROPERTY,
    WINID_CHANGEPROPERTY,

    WINID_INSTANCEINFO
};

#endif